volumes:
  node_modules:
services:
  development:
    image: node:16.13.0-alpine
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    working_dir: /app
    ports:
     - 8081:8081
    command: tail -f /dev/null